baseURL = 'http://kms7530.github.io'
languageCode = 'ko-kr'
title = 'Minseok Kwak - dev'
theme = "archie"
copyright = "© Athul"

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	katex = true # enable KaTeX support