baseURL = 'dev.minseok.me'
languageCode = 'ko-kr'
title = 'Minseok Kwak - dev'
theme = "archie"
copyright = "© Minseok Kwak"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	katex = true # enable KaTeX support

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4